# Generated by Django 4.2.2 on 2023-06-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AddField(
            model_name='places',
            name='rating',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
