# Generated by Django 4.2.2 on 2023-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_photos_options_alter_places_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
