# Generated by Django 4.2.2 on 2023-06-20 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_alter_places_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='places',
            name='website',
            field=models.TextField(blank=True),
        ),
    ]
