# Generated by Django 4.2.2 on 2023-06-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("web", "0005_alter_places_rating"),
        ("web", "0006_alter_places_rating"),
        ("web", "0007_alter_places_rating"),
        ("web", "0008_alter_places_rating"),
        ("web", "0009_alter_places_rating"),
        ("web", "0010_alter_places_rating"),
        ("web", "0011_alter_places_rating"),
        ("web", "0012_alter_places_rating"),
        ("web", "0013_alter_places_rating"),
        ("web", "0014_alter_places_rating"),
    ]

    dependencies = [
        ("web", "0004_places_created_by_alter_places_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name="places",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
