# Generated by Django 4.2.2 on 2023-07-03 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_places_rating_squashed_0014_alter_places_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="publicId",
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
