# Generated by Django 4.2.2 on 2023-07-05 10:33

from django.db import migrations, models
from django.utils.text import slugify

from web.models import Places

def create_name_slug(apps, schema_editor):
    places = Places.objects.all()
    for place in places:
        if place.slug == "" or place.slug is None:
            place.slug = slugify(place.name)
    Places.objects.bulk_update(places, fields=['slug'])

class Migration(migrations.Migration):
    dependencies = [
        ("web", "0015_reviews_publicid"),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='slug',
            field=models.CharField(unique=True, default=""),
            preserve_default=False,
        ),
        migrations.RunPython(create_name_slug, migrations.RunPython.noop)
    ]
